spring.application.name=Spring_JWT
spring.security.user.name=lavish
spring.security.user.password=1234
spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDB
spring.datasource.username=postgres
spring.datasource.password=123456

server.port=8090

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update